services:
  web:
    image: arm64v8/node:20 # Use the official Node.js 20 image
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    
    command: >
      sh -c "npm install -g @nestjs/cli && npm install && npm run start:dev"
    depends_on:
      - db

  db:
    image: arm64v8/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: arm64v8/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "6060:80"
    depends_on:
      - db

volumes:
  db_data:
